# Name of the workflow
name: Release

# Runs manually with major version, minor version and patch as input
on:
  workflow_dispatch:
    inputs:
      major:
        description: 'major version'
        required: true
      minor:
        description: 'minor version'
        required: true
      patch:
        description: 'patch'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build project with Maven
        run: mvn -B -ntp install
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: http://localhost:8081/repository/maven-central/
        username: admin
        password: ${{ secrets.password }}
        format: maven2
        repository: maven-central
        coordinates: groupId=com.devonfw artifactId=app version=${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}
        assets: extension=tar.gz
        filename: ./devonfw-ide-scripts-${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}.tar.gz
  # create release
  release:
    needs: build
    #needs: [test-windows, test-macos, test-ubuntu, build]
    runs-on: ubuntu-latest
    steps:      
      # Create github release with the specified tag, name and body
      - name: create gitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: Release/${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}
          name: ${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}
          body: |
                # Download
                https://repo1.maven.org/maven2/com/devonfw/tools/ide/devonfw-ide-scripts/${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}/devonfw-ide-scripts-${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}.tar.gz
                
                # Changes
                https://github.com/devonfw/ide/blob/master/CHANGELOG.asciidoc#${{ github.event.inputs.major }}${{ github.event.inputs.minor }}${{ github.event.inputs.patch }}
        
