# Name of the workflow
name: Release

# Run on every commit tag which begins with "release/" (e.g., "release/2022.09.001")
on:
  push:
    tags:
      - "release/*"

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
