# Name of the workflow
name: Release

# Run on every dispatch with release tag as input
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'release tag'
        default: 'latest'

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  create-release:
    # Create release 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: zip files
        uses: vimtor/action-zip@v1
        with:
          files: ./
          dest: './bin/ide-release-${{ github.event.inputs.release }}.zip'

      - name: gitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: Release/${{github.event.inputs.release}}
          name: ${{github.event.inputs.release}}
          body: '# Download\nhttps://repo1.maven.org/maven2/com/devonfw/tools/ide/devonfw-ide-scripts/2022.04.003/devonfw-ide-scripts-2022.04.003.tar.gz\n
                # Changes\nhttps://github.com/devonfw/ide/blob/master/CHANGELOG.asciidoc#202204003'
          artifacts: './bin/ide-release-${{ github.event.inputs.release }}.zip'