# Name of the workflow
name: Release

# Run on every dispatch with release tag as input
on:
  workflow_dispatch:
    inputs:
      major:
        description: 'major version'
        required: true
      minor:
        description: 'minor version'
        required: true
      patch:
        description: 'patch'
        required: true

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  test-windows:
    uses: ahmedagdmoun/devonfw-ide/.github/workflows/test-windows.yml@test
  test-macos:
    uses: ahmedagdmoun/devonfw-ide/.github/workflows/test-macos.yml@test
  test-ubuntu:
    uses: ahmedagdmoun/devonfw-ide/.github/workflows/test-ubuntu.yml@test
  build:
    uses: ahmedagdmoun/devonfw-ide/.github/workflows/build.yml@test
  release:
    needs: [test-windows, test-macos, test-ubuntu, build]
    runs-on: ubuntu-latest
    steps:      
      # Create release 
      - name: create gitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: Release/${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}
          name: ${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}
          body: |
                # Download
                https://repo1.maven.org/maven2/com/devonfw/tools/ide/devonfw-ide-scripts/${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}/devonfw-ide-scripts-${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}.tar.gz
                
                # Changes
                https://github.com/devonfw/ide/blob/master/CHANGELOG.asciidoc#${{ github.event.inputs.major }}${{ github.event.inputs.minor }}${{ github.event.inputs.patch }}
        
