# Name of the workflow
name: Release

# Run on every dispatch with release tag as input
on:
  worklflow_dispatch:
    inputs:
      release:
        description: 'release tag'
        default: 'latest'

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.inputs.release }}"
          prerelease: false
